// Pokemon sprite ids under assets/icons.

export const POKEMON_ICONS: ReadonlyArray<string> = [
  "bayleef",
  "blastoise",
  "blaziken",
  "bulbasaur",
  "charizard",
  "charmander",
  "charmeleon",
  "chikorita",
  "combusken",
  "croconaw",
  "cyndaquil",
  "feraligatr",
  "gengar",
  "grovyle",
  "ivysaur",
  "marshtomp",
  "meganium",
  "mudkip",
  "quilava",
  "sceptile",
  "squirtle",
  "swampert",
  "torchic",
  "totodile",
  "treecko",
  "typhlosion",
  "venusaur",
  "wartortle",
]
